# Generated by Django 5.2.8 on 2025-11-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('cosas_que_le_gustan', models.TextField(blank=True)),
                ('cosas_que_le_afectan', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('deportes', models.TextField(blank=True)),
                ('musica', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
